version: "3.8"
services:
  echo-server-test:
    image: mendhak/http-https-echo:30
    environment:
      HTTP_PORT: 8000

  nginx-test:
    # name required for Healthy Container CI/CD check
    container_name: "nginx-test"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NGINX_LOGS_INCLUDE_STATUS_CODE_REGEX: $NGINX_LOGS_INCLUDE_STATUS_CODE_REGEX
      NGINX_PORT: 8001
      APP_PORT: 8000
      APP_HOST: echo-server-test
    ports:
      - 8001:8001
    depends_on:
      - echo-server-test

  wait-test:
    image: deliveroo/circleci:1.7
    links:
      - nginx-test
